Feat/#30/add ui
sewonkimm/MojimojiMemoji pull request #31
Opened 2020-05-14 14:53 UTC by sewonkimm

2020-05-16 17:04 UTC, soyoungjeong approved these changes

2020-05-16 17:15 UTC, JaeHyeonKim19 requested changes
몇 가지 의문사항있어서 리뷰남겼습니다. 확인 부탁드려요.

2020-05-16 17:15 UTC, JaeHyeonKim19 commented on app/src/components/FolderMore/styles.scss
> +    margin-right: 1.3rem;
margin-right에만 다른 단위를 쓰셨는데 특별한 이유가 있을까요?

2020-05-16 17:15 UTC, JaeHyeonKim19 commented on app/src/components/FolderMore/index.tsx
> +const FolderMore = () => {
FolderMore이라는 변수명을 봤을 때 어떤 기능을 하는 컴포넌트인지 정확하게 알기 어려운 것 같아요. 어떻게 생각하시나요?

2020-05-16 17:15 UTC, JaeHyeonKim19 commented on app/src/components/FolderMore/styles.scss
> +  margin-top: 1.5rem;
여기도 rem을 사용하셨네요! 이유를 알 수 있을까요?

2020-05-16 17:15 UTC, JaeHyeonKim19 commented on app/src/components/MemoMore/styles.scss
> +  margin-top: 1.5rem;
여기도 rem 관련해서 궁금하네요!

2020-05-16 17:18 UTC, soyoungjeong requested changes
추가로 memo edit 페이지에서는 Header에 선택 아이콘이 안나오도록 추후에 처리하는 것이 좋을 것 같네요 !

2020-05-16 17:18 UTC, soyoungjeong commented on app/src/components/FolderMore/index.tsx
> +      </div>
'폴더 이동' 기능 말고 '이름 변경' 기능이었던 것 같은데 폴더 이동도 있었나요??

2020-05-16 17:18 UTC, soyoungjeong commented on app/src/components/Header/styles.scss
> +.homeBtnDiv {
전 보통 class명을 지을때 하이픈이나 언더라인을 많이 써서 어떤 것으로 할지 함께 정하면 좋을 것 같아요 !

2020-05-17 03:51 UTC, sewonkimm commented on app/src/components/MemoMore/styles.scss
> +  margin-top: 1.5rem;
rem 은 별 의미가 없이 사용했습니다. rem을 사용하는 것보다 px로 고정시키는게 좋은가요?

2020-05-17 03:54 UTC, sewonkimm commented on app/src/components/FolderMore/index.tsx
> +const FolderMore = () => {
Folder 에 대한 부가적 기능을 뭐라고 표현해야할지... more버튼에서 그대로 따와서 FolderMore라고 지었는데 [폴더 이동 및 삭제, 이름 변경, 색상변경]등을 반영한 변수명으로 아이디어 있을까요?

2020-05-17 03:55 UTC, sewonkimm commented on app/src/components/FolderMore/index.tsx
> +      </div>
폴더 이동은 없었습니다! Figma와 수정에 반영하겠습니다~

2020-05-17 07:01 UTC, sewonkimm commented on app/src/components/Header/styles.scss
> +.homeBtnDiv {
**class 명 지을 때 언더바 사용하기** 📌

2020-05-17 07:08 UTC, sewonkimm commented on app/src/components/Header/styles.scss
> +.homeBtnDiv {
scss 코딩 컨벤션에 class 네이밍 권장에 따라서 언더바를 사용하기로 했습니다.

2020-05-17 07:17 UTC, sewonkimm commented on app/src/components/FolderMore/index.tsx
> +const FolderMore = () => {
**FolderSetting으로 변경**

2020-05-17 07:17 UTC, sewonkimm commented on app/src/components/FolderMore/index.tsx
> +      </div>
#34

2020-05-17 07:17 UTC, soyoungjeong commented on app/src/components/MemoMore/styles.scss
> +  margin-top: 1.5rem;
rem과 px이 함께 쓰이면 글꼴 크기가 바뀔 때 비율이 깨질 수도 있을 것 같아요! 프로젝트 전체에 rem 또는 px로 통일 하는 것이 좋을 것 같은데 px로 통일하시죠!!

2020-05-21 14:24 UTC, sewonkimm commented
디자인에 대한 의견을 반영 #34

2020-05-21 14:25 UTC, sewonkimm commented
MemoEdit 페이지에 저장버튼 추가 #36

2020-05-21 15:30 UTC, soyoungjeong requested changes

2020-05-21 15:30 UTC, soyoungjeong commented on app/src/components/Header/styles.scss
> +}
제가 불러서 확인해봤을 때는 저장 버튼이 선택 버튼으로 보입니다!

2020-05-21 15:30 UTC, JaeHyeonKim19 approved these changes
수고하셨어요👍

2020-05-21 16:49 UTC, sewonkimm commented on app/src/components/Header/styles.scss
> +}
네 정상입니다! 일단 display 설정을 none 으로 해놓았습니다.
edit 페이지 기능 구현하면서 header 설정도 바꿔줄 예정입니다.

2020-05-22 01:52 UTC, soyoungjeong approved these changes

2020-05-22 14:39 UTC, merged