[feat] #36 header button을 url에 따라 조정
sewonkimm/MojimojiMemoji pull request #39
Opened 2020-05-23 16:25 UTC by sewonkimm

props에 path 값을 전달해 보내서 url에 맞는 버튼만 보이도록 렌더링

2020-05-23 17:40 UTC, soyoungjeong requested changes

2020-05-23 17:40 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +}
Props는 다른 곳에서 사용하지 않으니 export 하지 않아도 될 것 같습니다!

2020-05-23 17:40 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +  const [back, setBack] = useState(false);
type이 true일 경우에는 변수명을 is 나 has 등으로 시작하는 것이 좋을 것 같아요! 
참고글 : https://soojin.ro/blog/naming-boolean-variables 등등

2020-05-23 17:40 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +      {back ? <div className={styles.back_btn} /> : null}
`{ back && <div className={styles.back_btn} />}`
이런식이 가독성이 더 높아보이는데 어떠신가요??

2020-05-23 17:40 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +  });
useEffect는 두번째인자로 배열을 꼭 넣어주는 것이 좋습니다 : )

2020-05-23 17:45 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +    if (path == 'folder-list') {
비교는 === 으로ㅎㅎ 오타인 것 같아용

2020-05-25 09:13 UTC, JaeHyeonKim19 approved these changes
수고하셨습니다.

2020-05-28 17:30 UTC, soyoungjeong commented on app/src/components/Header/index.tsx
> +  const toggleSelect = () => {
이름이 동사+동사라 좀 어색한듯 하기도 하네요ㅎㅎ toggleSelectBtn 이나 handleSelectBtnClick 등은 어떨까요??

2020-05-28 17:56 UTC, sewonkimm commented on app/src/components/Header/index.tsx
> +  const toggleSelect = () => {
앗 그렇네요! 동사+명사로 수정해보겠습니다 👍

2020-05-31 06:53 UTC, soyoungjeong approved these changes
수고하셨습니다 :)

2020-05-31 07:00 UTC, merged